# Generated by Django 4.1.4 on 2023-01-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='avaliable',
            new_name='available',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='image',
        ),
    ]
