# Generated by Django 4.1.4 on 2023-01-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_rename_avaliable_coffee_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='available',
        ),
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ImageField(default='coffee/default_coffee_image.jpg', upload_to='coffee/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='price',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
