# Generated by Django 4.1.4 on 2023-01-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_remove_coffee_available_coffee_image_coffee_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(upload_to='coffee/%Y/%m/%d/'),
        ),
    ]
