# Generated by Django 4.1.4 on 2023-01-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_alter_coffee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
